services:
  order-db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: order_db
    ports:
      - "5433:5432"

  payment-db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: payment_db
    ports:
      - "5434:5432"

  notification-db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: notification_db
    ports:
      - "5435:5432"

  rabbitmq:
    image: rabbitmq:3-management-alpine
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

  order-service:
    build:
      context: ./order-service
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - order-db
      - payment-service
    environment:
      - PAYMENT_SERVICE_ADDR=payment-service:50051
      - DB_SOURCE=postgresql://user:password@order-db:5432/order_db?sslmode=disable

  payment-service:
    build:
      context: ./payment-service
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
      - "50051:50051"
    depends_on:
      - payment-db
      - rabbitmq
    environment:
      - GRPC_PORT=50051
      - DB_SOURCE=postgresql://user:password@payment-db:5432/payment_db?sslmode=disable
      - RABBITMQ_URL=amqp://guest:guest@rabbitmq:5672/

  notification-service:
    build:
      context: ./notification-service
      dockerfile: Dockerfile
    depends_on:
      - notification-db
      - rabbitmq
    environment:
      - DB_SOURCE=postgresql://user:password@notification-db:5432/notification_db?sslmode=disable
      - RABBITMQ_URL=amqp://guest:guest@rabbitmq:5672/